USE [master]
GO


-- DROP DATABASE Wikipedia;

/****** Object:  Database [Wikipedia]    Script Date: 2014-10-30 09:53:57 ******/
CREATE DATABASE [Wikipedia]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Wikipedia1_1', FILENAME = N'G:\SQLData\Wikipedia1_1.mdf' , SIZE = 8GB , MAXSIZE = UNLIMITED, FILEGROWTH = 256MB ),
 FILEGROUP [SECONDARY] 
( NAME = N'Wikipedia2_1', FILENAME = N'H:\SQLData\Wikipedia2_1.ndf' , SIZE = 4GB , MAXSIZE = UNLIMITED, FILEGROWTH = 256MB )
 LOG ON 
( NAME = N'Wikipedia_log', FILENAME = N'H:\SQLLogs\Wikipedia_log.ldf' , SIZE = 256MB , MAXSIZE = 8GB , FILEGROWTH = 256MB )
GO

ALTER DATABASE [Wikipedia] ADD FILEGROUP [SPAN]
GO
ALTER DATABASE [Wikipedia] ADD FILE ( NAME = N'WikipediaSpan_1', FILENAME = N'G:\SQLData\WikipediaSpan_1.ndf' , SIZE = 4GB, FILEGROWTH = 256MB ) TO FILEGROUP [SPAN]
GO
ALTER DATABASE [Wikipedia] ADD FILE ( NAME = N'WikipediaSpan_2', FILENAME = N'H:\SQLData\WikipediaSpan_2.ndf' , SIZE = 4GB, FILEGROWTH = 256MB ) TO FILEGROUP [SPAN]
GO


ALTER DATABASE [Wikipedia] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Wikipedia].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Wikipedia] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Wikipedia] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Wikipedia] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Wikipedia] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Wikipedia] SET ARITHABORT OFF 
GO

ALTER DATABASE [Wikipedia] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Wikipedia] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Wikipedia] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Wikipedia] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Wikipedia] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Wikipedia] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Wikipedia] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Wikipedia] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Wikipedia] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Wikipedia] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Wikipedia] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Wikipedia] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Wikipedia] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Wikipedia] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Wikipedia] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Wikipedia] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Wikipedia] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Wikipedia] SET RECOVERY BULK_LOGGED WITH NO_WAIT
GO

ALTER DATABASE [Wikipedia] SET  MULTI_USER 
GO

ALTER DATABASE [Wikipedia] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Wikipedia] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Wikipedia] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Wikipedia] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Wikipedia] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Wikipedia] SET  READ_WRITE 
GO


